//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.17 at 02:42:08 PM PYST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://sigh.med.una.py/2013/schemas/base")
package py.una.med.base.menu.schemas;
