/*-
 * Copyright (c)
 *
 * 		2012-2014, Facultad Politécnica, Universidad Nacional de Asunción.
 * 		2012-2014, Facultad de Ciencias Médicas, Universidad Nacional de Asunción.
 * 		2012-2013, Centro Nacional de Computación, Universidad Nacional de Asunción.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.1-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.10.18 at 09:31:38 AM PYST
//

package py.una.pol.karaku.menu.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="menu" type="{http://sigh.med.una.py/2013/schemas/base}Menu"/>
 *         &lt;element name="skipRoot" type="string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 * </p>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "menu", "skipRoot" })
@XmlRootElement(name = "menuResponse")
public class MenuResponse {

	@XmlElement(required = true)
	private Menu menu;

	@XmlElement(required = true)
	private String skipRoot;

	/**
	 * Gets the value of the menu property.
	 *
	 * @return possible object is {@link Menu }
	 *
	 */
	public Menu getMenu() {

		return menu;
	}

	/**
	 * Sets the value of the menu property.
	 *
	 * @param value
	 *            allowed object is {@link Menu }
	 *
	 */
	public void setMenu(Menu value) {

		this.menu = value;
	}

	/**
	 * @return skipRoot
	 */
	public String getSkipRoot() {

		return skipRoot;
	}

	/**
	 * @param skipRoot
	 *            skipRoot para setear
	 */
	public void setSkipRoot(String skipRoot) {

		this.skipRoot = skipRoot;
	}

}
