//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.1-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.10.18 at 09:31:38 AM PYST
//

package py.una.med.base.menu.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="menu" type="{http://sigh.med.una.py/2013/schemas/base}Menu"/>
 *         &lt;element name="skipRoot" type="string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 * </p>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "menu", "skipRoot" })
@XmlRootElement(name = "menuResponse")
public class MenuResponse {

	@XmlElement(required = true)
	private Menu menu;

	@XmlElement(required = true)
	private String skipRoot;

	/**
	 * Gets the value of the menu property.
	 *
	 * @return possible object is {@link Menu }
	 *
	 */
	public Menu getMenu() {

		return menu;
	}

	/**
	 * Sets the value of the menu property.
	 *
	 * @param value
	 *            allowed object is {@link Menu }
	 *
	 */
	public void setMenu(Menu value) {

		this.menu = value;
	}

	/**
	 * @return skipRoot
	 */
	public String getSkipRoot() {

		return skipRoot;
	}

	/**
	 * @param skipRoot
	 *            skipRoot para setear
	 */
	public void setSkipRoot(String skipRoot) {

		this.skipRoot = skipRoot;
	}

}
